openapi: 3.0.1
info:
  title: TempAPI
  description: API Definition of TempAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/tempapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
