openapi: 3.0.1
info:
  title: Demojenkins
  description: API Definition of Demojenkins
  version: 1.0.0
servers:
- url: http://localhost:8290/Demojenkins
paths:
  /:
    get:
      responses:
        default:
          description: Default response
